# 1260 steps in a 105 second game. All values are based off of this
# train every 10 games, with opponent every 20 games

engine_settings:
  time_scale: 60
  capture_frame_rate: 60
  target_frame_rate: -1
  quality_level: 1
checkpoint_settings:
  run_id: training_run
  force: true
  resume: false
  train_model: true
torch_settings:
  device: cpu
behaviors:
  15robot:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 12600
      learning_rate: 1.0e-4
      learning_rate_schedule: constant

      num_epoch: 2

    network_settings:
      vis_encode_type: simple
      normalize: true
      hidden_units: 512
      num_layers: 4

    summary_freq: 12600
    max_steps: 2000000

    self_play:
      window: 1
      play_against_latest_model_ratio: 1.0
      save_steps: 12600
      swap_steps: 25200
      team_change: 25200
