engine_settings:
  time_scale: 60
  capture_frame_rate: 60
checkpoint_settings:
  run_id: testing
  resume: true
  force: true
  train_model: true
torch_settings:
  device: cpu
behaviors:
  15robot:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 1.0e-4
      learning_rate_schedule: linear

      num_epoch: 2

    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 512
      num_layers: 4

    summary_freq: 10000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 10000
      swap_steps: 20000
      team_change: 40000
